### PR TITLE
Port loki/#10752 to Agent

### PR DESCRIPTION
**Pull request by salvacorts**
#### PR Description
This PR upstreams the promtail changes from https://github.com/grafana/loki/pull/10752 into the Grafana Agent.

This is rather expected behavior, so no need to update the docs.

#### PR Checklist

- [x] CHANGELOG.md updated
- [ ] Documentation added
- [ ] Tests updated
- [ ] Config converters updated

### CODE REVIEW

**Review by tpaschalis — APPROVED** [review]
LGTM, thanks for porting the changes over @salvacorts!

**Comment by alexinfoblox** [comment]
Is this feature available in the v0.39.0 release? 
Trying to extract labels into the `structed_metadata`, however, discovered labels are getting added to the stream.
Config:
```
scrape_configs:
- job_name: kubernetes-pods
  pipeline_stages:
    - cri: {}
    - structured_metadata:
        container_image:
        app_version:
  kubernetes_sd_configs:
    - role: pod
  relabel_configs:
    - source_labels:
      - __meta_kubernetes_pod_label_app_kubernetes_io_version
      action: replace
      target_label: app_version
    - source_labels:
      - __meta_kubernetes_pod_container_image
      action: replace
      target_label: container_image
```
In the Loki there are duplicated labels:
image
image
 
And discovered labels getting added to the Label Filters 
image


When I'm trying to use this `structed_metadata` in [Promtail ](https://github.com/grafana/loki/pull/10752)(using the latest image) with the same configuration, the feature works as expected. The extracted labels are not being added to the stream as new labels.

Why this doesn't work in Grafana-Agent?

**Comment by mattdurham** [comment]
This was only added to flow mode and it looks like you are using static mode.

**Comment by alexinfoblox** [comment]
Yeah. I'm using static mode. 
Ok, will give it a try with flow mode. @mattdurham Thanks for the pointer

**Pull request merged**
