### PR TITLE
Prefix binaries with "grafana-"

### LINKED ISSUE #582: Rename binary to grafana-agent-* ?
In particular with https://github.com/prometheus/prometheus/pull/8785 it would make sense to be more specific in naming with the binary, I think.

### PR DESCRIPTION
**Pull request by rfratto**
#### PR Description 
Prefixes binaries with `grafana-` to make then more unique compared to just being called "agent."

#### Which issue(s) this PR fixes 
Closes #582

#### Notes to the Reviewer
We'll need to be careful with this one since it touches every part of the build process and CI.

#### PR Checklist

- [x] CHANGELOG updated 
- [x] Documentation added
- [x] Tests updated

### CODE REVIEW

**Review by mattdurham — COMMENTED** [review]
I think the changes are fine but what about any docs on Grafana.com?

**Comment by rfratto** [comment]
Yeah, that's a good point. Depending on what docs exist, not much may need to change (the deb/rpm) system packages already used these names for the installed binaries.  

This should probably wait until after 0.16.0 so we allow for more time to coordinate with the docs team. 


cc @matthewhelmke

**Comment by matthewhelmke** [comment]
Take a look and let me know if you find any docs in need of edits. I'm happy to help with making some changes. I can't recall any instances off the top of my head.
I'll be free to help look next week.

**Comment by rfratto** [comment]
This is so stale that I'm going to close this. This would benefit from a new PR from scratch once we have our docs synced.

**Pull request closed without merging**
