### PR TITLE
feat(faro/receiver): propagate request metadata to downstream consumers

### LINKED ISSUE #6503: Add an `include_metadata` argument to `faro.receiver`
### Request

The [faro.receiver](https://grafana.com/docs/agent/latest/flow/reference/components/faro.receiver/) Flow component does not have the `include_metadata` config argument which otelcol receivers such as [otelcol.receiver.otlp](https://grafana.com/docs/agent/latest/flow/reference/components/otelcol.receiver.otlp/) tend to have. 

### Use case

This makes it harder for users to set the tenant ID in the outgoing request's headers using the `from_context` argument of [otelcol.auth.headers](https://grafana.com/docs/agent/latest/flow/reference/components/otelcol.auth.headers/).

### PR DESCRIPTION
**Pull request by hainenber**
#### Which issue(s) this PR fixes

Fixes #6503 

#### Notes to the Reviewer

Added a E2E test for the whole flow but afraid that it's plagued with data race 😞 . Hope this can be circumvented by running the test without the race detector.

#### PR Checklist

- [x] CHANGELOG.md updated
- [x] Documentation added
- [x] Tests updated

### CODE REVIEW

**Review by clayton-cornell — COMMENTED** [review]
Doc change is small. Over to Agent team for code review.

**Review by ptodev — APPROVED** [review]
Thank you, and apologies for the late review! If it's hard to get the test working, maybe a simpler test will do for now?

**Review by clayton-cornell — APPROVED** [review]

**Comment by clayton-cornell** [comment]
This one is still sitting in my ToDos...
@hainenber there are some conflicts here that need to be resolved.
@ptodev is it ready for merge from your side once the conflicts are sorted?

**Comment by hainenber** [comment]
I've resolved the merge conflict. Re: simpler test for the change, most of metadata handling logic comes from internals of OpenTelemetry collectors so a E2E test is pretty much warranted. I think we can skip running data race for this particular test for the time being.

**Comment by rfratto** [comment]
@hainenber I'm really sorry about how long this (and your other PRs) have been sitting around; we've all been super busy preparing for GrafanaCon. Working on helping getting this merged now :)

**Comment by hainenber** [comment]
@rfratto no worries, the more GA users from GrafanaCon, the better for me also :D

Thanks for checking out my past PRs!

**Pull request merged**
