### PR TITLE
Update migrating-from-static.md

### PR DESCRIPTION
**Pull request by mikempx**
Running existing static to flow conversion with "grafana-agent" insinuated that I still needed the old agent. By default, the executable is named, "grafana-agent-flow" in the documentation and doesn't mention a need to rename the executable.

#### PR Checklist

- [ ] CHANGELOG.md updated
- [ ] Documentation added
- [ ] Tests updated
- [ ] Config converters updated

### CODE REVIEW

**Comment by clayton-cornell** [comment]
@erikbaranowski Can you take a look at this? Is this the right solution or is there something else going on here that we need to account for?

**Comment by clayton-cornell** [comment]
@mikempx Can you sign the CLA whenyou get a chance :-)

**Comment by erikbaranowski** [comment]
@clayton-cornell the converter will work with either binary. It requires the env var only for the grafana-agent binary since Flow mode is not the default. I'm comfortable with documenting it in the converter guides however makes sense for clarity and consistency.

**Comment by clayton-cornell** [comment]
@erikbaranowski maybe we document it both ways? 

If you're using Grafana Agent static mode: `AGENT_MODE=flow grafana-agent convert --source-format=static --bypass-errors --output=OUTPUT_CONFIG_PATH INPUT_CONFIG_PATH`

If you're using Grafana Agent flow mode: `grafana-agent-flow convert --source-format=static --bypass-errors --output=OUTPUT_CONFIG_PATH INPUT_CONFIG_PATH`

**Comment by erikbaranowski** [comment]
I'm good with documenting both since we have done so in places like here: https://grafana.com/docs/agent/latest/flow/reference/cli/run/.

Let's update all 3 migration guides if we are making this change for consistency.

**Comment by clayton-cornell** [comment]
@mikempx I'm going to close this PR. Your request resulted in a larger change to the docs than was implemented here and it was easier/faster and cleaner to open a new PR to take care of the change.

The new PR is: https://github.com/grafana/agent/pull/5544

**Pull request closed without merging**
