### PR TITLE
feat: use k8s-alpha

### PR DESCRIPTION
**Pull request by Duologic**
Move on from the deprecated ksonnet library.

### CODE REVIEW

**Comment by rfratto** [comment]
Thanks for working on this! This is a pretty massive thing to review, and I'm leaning towards trust with a rubber stamp here. Has this  been tested to make sure it still works? If not, I can spend some time testing it myself before approving and mergng.

**Comment by Duologic** [comment]
It is what it is, not much draft anymore, 99% of the change is a vendoring, so not so massive. We've been running k8s-alpha for a while now in production (deployment_tools), where also grafana-agent runs, does that count as tested?

**Comment by rfratto** [comment]
> It is what it is, not much draft anymore, 99% of the change is a vendoring, so not so massive. 

I understand, there's just a lot of changed files and it's hard to review through the Github UI. 

> We've been running k8s-alpha for a while now in production (deployment_tools), where also grafana-agent runs, does that count as tested?

If this specific change has been tested, then yes! If not, I quickly ran the [k3d example](https://github.com/grafana/agent/tree/master/example/k3d) to validate this and everything LGTM. Once it's out of draft, I'm happy to approve and merge.

**Comment by Duologic** [comment]
I did the k3d example too (with tanka 0.11.1 and jb 0.4.0).

**Pull request merged**
