### PR TITLE
add description for source url in app receiver agent doc

### PR DESCRIPTION
**Pull request by shubhamgavali70**
#### PR Description
Updated the documentation of app agent receiver, which will provide context of source url

#### Notes to the Reviewer
I was struggling to upload sourcemaps because of this missing information, thought to add in the doc

#### PR Checklist

- [ ] CHANGELOG.md updated
- [x] Documentation added
- [ ] Tests updated
- [ ] Config converters updated

### CODE REVIEW

**Review by clayton-cornell — COMMENTED** [review]
Looks OK to me.

@shubhamgavali1998 can you sign the CLA so we can move forward with this PR.

@grafana/grafana-agent-maintainers Any input or comments from the team?

**Comment by shubhamgavali70** [comment]
> Looks OK to me.
> 
> @shubhamgavali1998 and @shubhamgavali70 can you sign the CLA so we can move forward with this PR.
> 
> @grafana/grafana-agent-maintainers Any input or comments from the team?

Done @clayton-cornell

**Comment by clayton-cornell** [comment]
@grafana/grafana-agent-maintainers I just want a double check from your side before I merge.

**Comment by shubhamgavali70** [comment]
> @grafana/grafana-agent-maintainers I just want a double check from your side before I merge.

Can we get this merged? @clayton-cornell

**Review by clayton-cornell — APPROVED** [review]

**Comment by clayton-cornell** [comment]
Sorry @shubhamgavali1998 I was offline for a few days. The change looks good to me and I don't see any blockers to merging. Packaging up and getting it published. :-)  Thanks for your input.

**Pull request merged**
