### PR TITLE
Add post method for config reload api

### LINKED ISSUE #610: Feature parity - requesting config reload API on Grafana Agent to match with Prometheus reload API
It would be nice to have the config reload API on Grafana Agent match with Prometheus reload API, for ease of use / operability 
 
Grafana Agent:
`GET /-/reload` 

Prometheus:
`PUT  /-/reload`
`POST /-/reload`

### PR DESCRIPTION
**Pull request by tharun208**
#### PR Description 
Add `POST` method for `reload` config http endpoint.

#### Which issue(s) this PR fixes 
Fixes #610

#### PR Checklist

- [ ] CHANGELOG updated 
- [x] Documentation added
- [ ] Tests updated

### CODE REVIEW

**Comment by tharun208** [comment]
also, I found that the `wal_directory` config for `Prometheus is missing in this file, can I check the config value for it in this PR?

**Review by rfratto — APPROVED** [review]
Perfect!

> also, I found that the wal_directory config for `Prometheus is missing in this file, can I check the config value for it in this PR?

I'm not sure I understand what you mean here, could you explain?

**Comment by tharun208** [comment]
> Perfect!
> 
> > also, I found that the wal_directory config for `Prometheus is missing in this file, can I check the config value for it in this PR?
> 
> I'm not sure I understand what you mean here, could you explain?

This https://github.com/grafana/agent/blob/main/cmd/agent/agent-local-config.yaml is missing the `wal_directory` value which failed when ran the locally built agent with the config file.
So, can I include the change with this same pr?

**Comment by rfratto** [comment]
Ah, thanks for explaining. The intent for that file was that users pass `--prometheus.wal-directory` as a flag since everyone will likely want to put it in a different place. I'd be fine with a change that configures `wal_directory` to a relative directory like `./data`, though.

**Comment by tharun208** [comment]
> Ah, thanks for explaining. The intent for that file was that users pass `--prometheus.wal-directory` as a flag since everyone will likely want to put it in a different place. I'd be fine with a change that configures `wal_directory` to a relative directory like `./data`, though.

ok, understood, then it is not required to include the change.

**Review by rfratto — APPROVED** [review]

**Pull request merged**
