### PR TITLE
docs: fix broken prometheus links

### PR DESCRIPTION
**Pull request by Dentrax**
Signed-off-by: Furkan <furkan.turkal@trendyol.com>

#### PR Description

Agent [uses Prometheus v1.8.2](https://github.com/grafana/agent/blob/d5b5dcf5c847c308d21b2e2fdad77339728f13f3/go.mod#L82) so correct documentation version should be `1.8` instead of `2.27`. The following link also broken:

https://prometheus.io/docs/prometheus/2.27/configuration/configuration/#remote_write

#### PR Checklist

- [ ] CHANGELOG updated
- [X] Documentation added
- [ ] Tests updated

### CODE REVIEW

**Comment by mattdurham** [comment]
Thanks for the submission and I updated the link in a PR 15 minutes ago.

**Comment by Dentrax** [comment]
> Thanks for the submission and I updated the link in a PR 15 minutes ago.

Oh, thanks for notifying me! Just checked your link and noticed target versions seems still pointing to the wrong version.

**Comment by mattdurham** [comment]
Though I didn't catch all the links so this still good to go. As far as versions due to the replace commands you have to backtrack and not depend on the semantic version.

**Comment by Dentrax** [comment]
> We are actually on 2.34, specifically this custom fork/branch [grafana/prometheus@`release-2.34.0-grafana` (commits)](https://github.com/grafana/prometheus/commits/release-2.34.0-grafana). If you want to change the links to those?

Sorry, I couldn't get. We are using Prometheus v1.8.2 client in [go.mod](https://github.com/grafana/agent/blob/d5b5dcf5c847c308d21b2e2fdad77339728f13f3/go.mod#L82=). I also don't see any Prometheus `v2.34` version in go.mod. Are we able to pass `2.34` configs to `1.8.2` client?

**Comment by rfratto** [comment]
The actual Prometheus v1.8.2 is from 2017, and is definitely not what we're actually using :)

**Comment by Dentrax** [comment]
Oh, thanks for clarification. Such great TIL!

**Review by brendamuir — APPROVED** [review]

**Comment by Dentrax** [comment]
Closing this one in favor of https://github.com/grafana/agent/pull/1859

**Pull request closed without merging**
