### PR TITLE
Update changelog

### PR DESCRIPTION
**Pull request by MarkDordoy**
#### PR Description
This PR updates the windows_exporter dependency to master. Full change log [here](https://github.com/grafana/windows_exporter/compare/fdb3ba7accd8..3391dcec6884)

#### PR Checklist

- [x] CHANGELOG.md updated

### CODE REVIEW

**Comment by MarkDordoy** [comment]
CC @mattdurham

**Comment by mattdurham** [comment]
Something doesn't look write with the go.mod, will try to poke at it today/tomorrow.

**Comment by MarkDordoy** [comment]
@mattdurham is this still something we can look at getting deployed please

**Comment by mattdurham** [comment]
Thanks to @jkroepke worked on the exporter we are going to be switching from our fork and using the upstream exporter. I have on blocker PR in windows_exporter that needs to be resolved then another PR for handling the changes ready to go. This will allow us to easily update windows_exporter in the future. Thank you for bringing this up. Going  to close this for now but this should be resolved entirely within a week.

**Pull request closed without merging**
