### PR TITLE
loki.process: add decolorise stage support

### PR DESCRIPTION
**Pull request by thampiotr**
#### PR Description

Part of https://github.com/grafana/agent/issues/4836
This fell through the cracks for feature parity. 

#### PR Checklist

- [x] CHANGELOG.md updated
- [x] Documentation added
- [x] Tests updated
- [x] Config converters updated

### CODE REVIEW

**Review by wildum — APPROVED** [review]
LGTM

**Comment by thampiotr** [comment]
I'll hold off with merging to let @clayton-cornell review the docs.

**Review by ptodev — APPROVED** [review]

**Comment by thampiotr** [comment]
> I'll hold off with merging to let @clayton-cornell review the docs.

I'll merge this now as I need some of the changes to continue more work on loki.process and the docs are heavily inspired by existing promtail docs. But if there are any requests to improve the docs, please let me know and I'll be fixing it.

**Comment by clayton-cornell** [comment]
@ptodev Dos are ok here :-)

**Pull request merged**
