### PR TITLE
Containerize merges to development branches

### PR DESCRIPTION
**Pull request by mapno**
#### PR Description

Containerizes merges in `dev.{}` branches. This will create a build and push it to Grafana's DockerHub.

#### Which issue(s) this PR fixes 

Closes https://github.com/grafana/agent/issues/892

#### PR Checklist

- [ ] CHANGELOG updated 
- [ ] Documentation added
- [ ] Tests updated

### CODE REVIEW

**Comment by mapno** [comment]
Should this get documented somewhere?

**Comment by rfratto** [comment]
> Should this get documented somewhere?

That's a good question. We don't really document the main branch images either, so we don't have to document this right now. 

I think once we document the new branching strategy we can reference that images for main and dev branches get pushed on merge.

**Review by mattdurham — CHANGES_REQUESTED** [review]
You need to resign the drone build but looks good other than that. 'make drone'

**Comment by mapno** [comment]
@mattdurham is it ok now? I restarted the CI build

**Comment by mattdurham** [comment]
Apologies should have written more =). We sign the drone.yaml so that the build process verifies the changes. I pushed the changes here and once the drone build finishes will merge.

**Review by mattdurham — APPROVED** [review]

**Pull request merged**
