### PR TITLE
feat(comp/cadvisor): allow user to disable collecting root Cgroup stats

### LINKED ISSUE #5700: Support cadvisor option disable_root_cgroup_stats
### Request

If running cadvisor directly, I can pass the disable_root_cgroup_stats to hide statistics coming from `/`. I would like to be able to configure this option in the agent embedded cadvisor as well

### Use case

As I'm already collecting statistics from node_exporter/exporter.unix, I want to avoid double-collecting them (which also makes it more complicated to correctly use the metrics in grafana, as eg container_cpu_usage_seconds_total will return both metrics for individual containers as well as this aggregated metric that covers the entire system)

### LINKED ISSUE #5708: Agent fails to start when if can't pull the git repo even if the repos is present locally already
### What's wrong?

When the Grafana Agent is started using the [git module](https://grafana.com/docs/agent/latest/flow/reference/components/module.git/) the agent will clone the repo and store it locally. Then after the first startup was successful, if the agent is restarted and the git server is unavailable the agent fails to start even tough the repo is stored on disk and the module file would be accessible. 

### Steps to reproduce

1. Configure the agent to use a git a repository
2. Start the Agent (wait for it to fully start and check that the repository is present in the agent data folder)
3. Check that the repository and files are cached locally:
```
root@bc82d36f2915:/# ls -la /var/lib/grafana-agent-flow/module.git.test/repo/
total 4
drwxr-xr-x. 1 root root  40 Nov  3 16:22 .
drwxr-xr-x. 1 root root  70 Nov  3 16:22 ..
drwxr-xr-x. 1 root root  52 Nov  3 16:22 .git
-rw-r--r--. 1 root root 267 Nov  3 16:22 prometheus.river
```
5. Switch the repository to private to make it inaccessible 
6. Start the Agent and observe that it fails to start

### System information

Windows Server 2022 & Ubuntu 22.04

### Software version

Grafana Agent v0.37.1

### Configuration

```text
module.git "test" {
  repository = "https://github.com/ntimo/grafana-agent-git-module-test.git"
  path       = "prometheus.river"
}
```

### Logs

```text
Error: /etc/config.river:1:1: Failed to build component: building component: failed to update repository "https://github.com/ntimo/grafana-agent-git-module-test.git": authentication required

1 |   module.git "test" {
  |  _^^^^^^^^^^^^^^^^^^^
2 | |   repository = "https://github.com/ntimo/grafana-agent-git-module-test.git"
3 | |   path       = "prometheus.river"
4 | | }
  | |_^
5 |   

Error: could not perform the initial load successfully
```

### PR DESCRIPTION
**Pull request by hainenber**
#### PR Description
Allow user to specify whether `cadvisor` to collect root `cgroup` statistics

#### Which issue(s) this PR fixes

Fixes #5700 

#### Notes to the Reviewer
Please help checking https://github.com/grafana/cadvisor/pull/2 as it's required for this PR to go through. Thanks! 

#### PR Checklist

- [x] CHANGELOG.md updated
- [x] Documentation added
- [x] Config converters updated

### CODE REVIEW

**Review by clayton-cornell — COMMENTED** [review]
Docs are OK as-is

**Comment by tpaschalis** [comment]
I've merged https://github.com/grafana/cadvisor/pull/2 (thanks for taking care of it!) so let's also update go.mod as well.

**Comment by tpaschalis** [comment]
cc @hainenber when you have some time, can we update go.mod to point at the your https://github.com/grafana/cadvisor/pull/2 change so we can go ahead with this?

**Review by rfratto — APPROVED** [review]
Thank you!

**Pull request merged**
