### PR TITLE
Add kafka traces receiver

### PR DESCRIPTION
**Pull request by mapno**
#### PR Description 

Adds the kafka receiver 

#### Which issue(s) this PR fixes 

Closes https://github.com/grafana/agent/issues/484

#### PR Checklist

- [x] CHANGELOG updated 
- [x] Documentation added
- [x] Tests updated

### CODE REVIEW

**Review by joe-elliott — APPROVED** [review]

**Review by rfratto — APPROVED** [review]
LGTM! Before I merge, can you update the changelog?

@joe-elliott Typically we add all the receivers to the [install manifest](https://github.com/grafana/agent/blob/main/production/kubernetes/build/templates/tempo/main.jsonnet) (rendered as YAML [here](https://github.com/grafana/agent/blob/main/production/kubernetes/agent-tempo.yaml)), but since the Kafka receiver works so differently, I don't think we can do the same thing here. WDYT?

**Comment by joe-elliott** [comment]
Yeah, agree, it doesn't belong in the install manifest. Is there a place that makes sense to document this new option?

**Comment by rfratto** [comment]
Our docs here are really weak. IMO for now let's just have a list [in the docs for tempo_instance_config](https://github.com/grafana/agent/blob/main/docs/configuration-reference.md#tempo_instance_config), something like:

```yaml
# Receiver configurations are mapped directly into the OpenTelmetry receivers block.
#   At least one receiver is required. Supported receivers: otlp, jaeger, kafka, [...]
#   Documentation for each receiver can be found at https://github.com/open-telemetry/opentelemetry-collector/blob/7d7ae2eb34b5d387627875c498d7f43619f37ee3/receiver/README.md
receivers:
```

**Comment by mapno** [comment]
Added the documentation and manually tested the receiver by modifying the docker-compose example. I didn't think it was worth modifying the code. Let me know if you want me to test it some other way (e.g. integration tests).

**Review by rfratto — APPROVED** [review]
Thanks again! I'll merge once the conflicts are resolved.

**Comment by mapno** [comment]
> Thanks again! I'll merge once the conflicts are resolved.

They should be solved now

**Pull request merged**
