### PR TITLE
docs: enhance tooling documentation

### PR DESCRIPTION
**Pull request by theSuess**
Moved the tooling section to where developers would expect it. Also added links to the emacs-mode and tree-sitter grammar

### CODE REVIEW

**Review by clayton-cornell — APPROVED** [review]
This makes sense to me.

**Comment by clayton-cornell** [comment]
@theSuess Question before we merge this change... in the original text, it was clear that the tools were community developed. Now it makes it look more like it's "official".... yet they exist in a private github repo. Do we want to either make it clear these are still community tools and not Grafana, or should they be moved out of the private repos?

**Comment by theSuess** [comment]
Good point, I've added back the `Experimental` declaration for now and will try to get these extensions under the Grafana umbrella

**Comment by clayton-cornell** [comment]
Looks good to me. Time to merge. :-)

**Pull request merged**
