### PR TITLE
Call out string operators

### PR DESCRIPTION
**Pull request by petewall**
Call out the string operators (just the "+" concatenation operator) by putting them into their own table.

#### PR Checklist

- [ ] CHANGELOG updated
- [X] Documentation added
- [ ] Tests updated

### CODE REVIEW

**Comment by petewall** [comment]
Does a change like this go into CHANGELOG?

**Comment by clayton-cornell** [comment]
> Does a change like this go into CHANGELOG?

I'd guess probably not since it's not new content or a new feature, it's a correction to content we already had.

**Review by clayton-cornell — APPROVED** [review]
Looks good

**Comment by clayton-cornell** [comment]
Since we discussed this already in Slack I'll merge this one.

**Pull request merged**
