### PR TITLE
Remove deprecated otelcol.exporter.jaeger

### LINKED ISSUE #5138: v0.38: Remove deprecated component otelcol.exporter.jaeger
Because of the upstream OpenTelemetry component being deprecated, otelcol.exporter.jaeger was deprecated in v0.35 with a scheduled removal in v0.38. 

otelcol.exporter.jaeger should be removed with the v0.38 release as planned.

Related to #3495.

### PR DESCRIPTION
**Pull request by hainenber**
#### Which issue(s) this PR fixes

Fixes #5138 

#### PR Checklist

- [x] CHANGELOG.md updated
- [x] Documentation removed

### CODE REVIEW

**Comment by hainenber** [comment]
Thanks for the heads-up, guess I still have time to fix the failed tests from the removal 😅

**Comment by rfratto** [comment]
Hey @hainenber, we're working on the v0.38 cycle now so we can merge this PR once the merge conflicts are resolved and the CI is green :)

**Comment by rfratto** [comment]
I don't know why this PR is causing unrelated tests to flake, but I'm looking into it so we can get this merged.

**Review by rfratto — APPROVED** [review]
Merging!

**Pull request merged**
