### PR TITLE
node_exporter: fix usage of diskstat flags

### LINKED ISSUE #3759: Cannot set the allowlist field in node_exporter's diskstat collector
The logic around the include/exclude fields for the diskstat collector in the node_exporter integration, that is also inherited by the prometheus.exporter.unix component was that a) the `device_exclude` field had a default value and b) the `device_exclude` and `device_include` fields were mutually exclusive.

This meant that the first field was always being set implicitly, and if the second was defined then node_exporter could not start. The following two config files failed to start the Agent, and there is no way to make use of `device_include`.

```yaml
integrations:
  node_exporter:
    enabled: true
    scrape_integration: true
    set_collectors:
      - "diskstats"
    diskstats_device_include: "/dev/vd.*"
```

```river
prometheus.exporter.unix {
	disk {
		device_include = "foo"
	}
}
```

### PR DESCRIPTION
**Pull request by tpaschalis**
#### PR Description
The current logic in the node_exporter integration, that was also inherited by the prometheus.exporter.unix component was that a) the `device_exclude` field had a default value and b) the `device_exclude` and `device_include` fields were mutually exclusive.

This meant that the first field was always being set implicitly, and if the second was defined then node_exporter could not start.

That means that the following two config files failed to start the Agent and there was no way to make use of `device_include`.

```yaml
integrations:
  node_exporter:
    enabled: true
    scrape_integration: true
    set_collectors:
      - "diskstats"
    diskstats_device_include: "/dev/vd.*"
```

```river
prometheus.exporter.unix {
	disk {
		device_include = "foo"
	}
}
```

This PR changes the logic of the two fields to allow the default value being set by having the include field _take precedence_, and making it so that when it is set, the exclude field be ignored.

#### Which issue(s) this PR fixes
Fixes #3759

#### Notes to the Reviewer
Do you think this is a bug that warrants a patch release? I'd lean towards no, but let me know if you think otherwise.

#### PR Checklist

- [X] CHANGELOG updated
- [X] Documentation added
- [ ] Tests updated

### CODE REVIEW

**Review by jcreixell — APPROVED** [review]
LGTM

**Comment by marius-kirkeeide** [comment]
I see that this is merged, but I'm on the latest version (0.35.2) and I still can't use device_include in Grafana Agent Flow mode.

`Failed to build component: building component: failed to create node_exporter: failed to parse device filter flags: device-exclude & device-include are mutually exclusive`

**Comment by marius-kirkeeide** [comment]
`Jul 31 15:31:42 ubuntu2204.localdomain grafana-agent-flow[12503]: Error: /etc/grafana-agent-flow.river:61:1: Failed to build component: building component: failed to create node_exporter: failed to parse device filter flags: device-exclude & device-include are mutually exclusive
Jul 31 15:31:42 ubuntu2204.localdomain grafana-agent-flow[12503]: 60 |
Jul 31 15:31:42 ubuntu2204.localdomain grafana-agent-flow[12503]: 61 |   prometheus.exporter.unix {
Jul 31 15:31:42 ubuntu2204.localdomain grafana-agent-flow[12503]:    |  _^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 31 15:31:42 ubuntu2204.localdomain grafana-agent-flow[12503]: 62 | |   set_collectors = [
Jul 31 15:31:42 ubuntu2204.localdomain grafana-agent-flow[12503]: 63 | |     "diskstats",
Jul 31 15:31:42 ubuntu2204.localdomain grafana-agent-flow[12503]: 64 | |   ]
Jul 31 15:31:42 ubuntu2204.localdomain grafana-agent-flow[12503]: 65 | |   disk {
Jul 31 15:31:42 ubuntu2204.localdomain grafana-agent-flow[12503]: 66 | |       device_include = "foo"
Jul 31 15:31:42 ubuntu2204.localdomain grafana-agent-flow[12503]: 67 | |   }
Jul 31 15:31:42 ubuntu2204.localdomain grafana-agent-flow[12503]: 68 | | }
Jul 31 15:31:42 ubuntu2204.localdomain grafana-agent-flow[12503]:    | |_^
Jul 31 15:31:42 ubuntu2204.localdomain grafana-agent-flow[12503]: 69 |
Jul 31 15:31:42 ubuntu2204.localdomain grafana-agent-flow[12503]: ts=2023-07-31T15:31:42.367762435Z level=error msg="failed to start reporter" err="context canceled"
Jul 31 15:31:42 ubuntu2204.localdomain grafana-agent-flow[12503]: Error: could not perform the initial load successfully`

`agent, version v0.35.2 (branch: HEAD, revision: cd74c43e)
  build user:       root@b9ef22154ecf
  build date:       2023-07-27T18:11:35Z
  go version:       go1.20.6
  platform:         linux/amd64
  tags:             netgo,builtinassets,promtail_journal_enabled`

**Comment by marius-kirkeeide** [comment]
If I just change it from include to exclude I get:

```
Jul 31 15:46:12 ubuntu2204.localdomain grafana-agent-flow[12704]: ts=2023-07-31T15:46:12.220124267Z level=info component=prometheus.exporter.unix collector=diskstats msg="Parsed flag --collector.diskstats.device-exclude" flag=foo
Jul 31 15:46:12 ubuntu2204.localdomain grafana-agent-flow[12704]: ts=2023-07-31T15:46:12.220285743Z level=info component=prometheus.exporter.unix msg="Enabled node_exporter collectors"
Jul 31 15:46:12 ubuntu2204.localdomain grafana-agent-flow[12704]: ts=2023-07-31T15:46:12.220345516Z level=info component=prometheus.exporter.unix collector=diskstats
Jul 31 15:46:12 ubuntu2204.localdomain grafana-agent-flow[12704]: ts=2023-07-31T15:46:12.220398032Z level=info controller_id= trace_id=0bb0292a320cd54b6153651441a58509 msg="finished node evaluation" node_id=prometheus.exporter.unix duration=962.322µs
```

**Comment by tpaschalis** [comment]
I can't reproduce with your configuration. @marius-kirkeeide are you sure you're updated to v0.35.2?

I think you're running the Agent as a systemd service, right? Can you check the binary location using systemctl commands and verifying its version from there?

**Comment by marius-kirkeeide** [comment]
Yes, I've installed the deb package on Ubuntu 22.04 and I'm running it as a systemd service.

```
● grafana-agent-flow.service - Vendor-neutral programmable observability pipelines.
     Loaded: loaded (/lib/systemd/system/grafana-agent-flow.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2023-07-31 16:03:32 UTC; 185ms ago
       Docs: https://grafana.com/docs/agent/latest/flow/
   Main PID: 3438 (grafana-agent-f)
      Tasks: 12 (limit: 9405)
     Memory: 28.9M
        CPU: 369ms
     CGroup: /system.slice/grafana-agent-flow.service
             └─3438 /usr/bin/grafana-agent-flow run --server.http.listen-addr 0.0.0.0:12345 --storage.path=/var/lib/grafana-agent-flow /etc/grafana-agent-flow.river
```

```
$ /usr/bin/grafana-agent-flow --version
agent, version v0.35.2 (branch: HEAD, revision: cd74c43e)
  build user:       root@b9ef22154ecf
  build date:       2023-07-27T18:11:35Z
  go version:       go1.20.6
  platform:         linux/amd64
  tags:             netgo,builtinassets,promtail_journal_enabled
```

**Comment by tpaschalis** [comment]
I've verified that the fix is indeed on v0.35.2 by also building from source on the same reported `revision`.

In any case, I'll look into it.

**Comment by tpaschalis** [comment]
@marius-kirkeeide just to be safe, have you tried restarting the systemd service, in case it's still not picked up the new binary (in case you've updated from a previous version)?

**Comment by marius-kirkeeide** [comment]
Just replace the default config with
```
prometheus.exporter.unix {
  disk {
    device_include = "foo"
  }
}
```
and run `systemctl start grafana-agent-flow.service`

**Comment by tpaschalis** [comment]
Thanks you again @marius-kirkeeide for the report and reproduction. I've verified the issue on my end as well.

I've created a new issue https://github.com/grafana/agent/issues/4670 to look into what's wrong and look into the fix; this seems to affect more versions than just v0.35.2.

**Comment by marius-kirkeeide** [comment]
Thank you for the swift response! I'll follow the new issue.

**Pull request merged**
