### PR TITLE
Log: Add 'country' to geoip pipeline-stage

### PR DESCRIPTION
**Pull request by superstes**
#### Which issue(s) this PR fixes

Maxmind provides multiple GeoIP2 databases.
The three most used ones are City, Country and ASN as they are also available as [free GeoLiteIP2 databases](https://dev.maxmind.com/geoip/geolite2-free-geolocation-data).

Some users might want/need to use the 'Country' database - so I added support for it.
A reason: If the user only has the 'Country' database licensed.

#### Notes to the Reviewer

I've now also added mmdb-specific tests.

To note: The minimal (1 record) testdata-databases are added for the sake of simplicity.

One could also:
* add the [mmdbwriter](https://github.com/maxmind/mmdbwriter) as (test-)dependency and build those database-binaries at test-runtime from JSON
* or download the [maxmind testdata](https://github.com/maxmind/MaxMind-DB/tree/main/test-data) on each test-run

#### PR Checklist

- [x] CHANGELOG.md updated
- [x] Documentation added
- [x] Tests updated
- [ ] Config converters updated

### CODE REVIEW

**Comment by superstes** [comment]
Related to: https://github.com/grafana/loki/pull/11378

**Review by clayton-cornell — COMMENTED** [review]
The doc is OK as-is (consistent with the rest of the topic)

**Review by tpaschalis — APPROVED** [review]
LGTM! Thank you for the contribution @superstes and for prioritizing the Agent feature first! 🙌

**Comment by tpaschalis** [comment]
@superstes I can't push to your branch :( 

The linter is complaining about the `"dummy"` and `"192.0.2.1"` occurences in component/loki/process/stages/geoip_test.go.

Could you please put them in a const to satisfy the linter so we can merge this?

**Comment by superstes** [comment]
@tpaschalis Sorry - did not mean to block it.
Lint-error should be fixed now.

**Review by clayton-cornell — APPROVED** [review]

**Comment by clayton-cornell** [comment]
@tpaschalis @superstes The build is passing now, so I'll get this one merged :-)

**Pull request merged**
