### PR TITLE
Flow tracing instrumentation: add support for Jaeger remote sampling

### PR DESCRIPTION
**Pull request by rfratto**
This PR adds a `sampling > jaeger_remote` block into the `tracing` configuration block, allowing users to retrieve sampling decisions from a server which supports exposing Jaeger `strategies.json` files.

### CODE REVIEW

**Comment by rfratto** [comment]
This is panicking when being run: 

```
panic: proto: duplicate enum registered: jaeger.api_v2.SamplingStrategyType

goroutine 1 [running]:
github.com/gogo/protobuf/proto.RegisterEnum(...)
	/Users/robert/dev/go/pkg/mod/github.com/gogo/protobuf@v1.3.2/proto/properties.go:520
go.opentelemetry.io/contrib/samplers/jaegerremote/internal/proto-gen/jaeger-idl/proto/api_v2.init.0()
	/Users/robert/dev/go/pkg/mod/go.opentelemetry.io/contrib/samplers/jaegerremote@v0.5.2/internal/proto-gen/jaeger-idl/proto/api_v2/sampling.pb.go:392 +0x244
exit status 2

```

**Comment by rfratto** [comment]
I worked around this by temporarily forking the jaegerremote module and opened an issue upstream so we can get rid of the fork ASAP.

**Review by mattdurham — APPROVED** [review]
LGTM

**Review by tpaschalis — APPROVED** [review]
LGTM

**Comment by karengermond** [comment]
> 

Looks good to me!

**Pull request merged**
