### PR TITLE
Create NOTICE.md

### PR DESCRIPTION
**Pull request by tonychoe**
Hello, 

Let's add a NOTICE.md to share the copyright information for this project.

I made one like the [one](https://github.com/grafana/grafana/blob/main/NOTICE.md) used for the Grafana project.

### CODE REVIEW

**Comment by tpaschalis** [comment]
Hey there 👋 

We already have a LICENCE associated with the project, I'm not sure the copyright notice is required here.
I'll take it up with the rest of the team and let you know if we need this here.

**Comment by raphaelfan** [comment]
Hi @tpaschalis , I was wondering if you can help unblock the merge? Thanks.

**Comment by rfratto** [comment]
Currently, we don't understand the legal implications behind adding NOTICE.md, especially if we forget to update the copyright year (which I'm sure we _will_ forget to do).

We've been waiting for advice from our legal team before taking action on this PR. I'm sorry that it's been sitting open for a while, but we're still actively waiting. We'll provide an update as soon as we have one.

**Comment by rfratto** [comment]
Hi, I'm going to close this for now as I'm still not sure what the legal implications behind this are, and most projects I looked at within the Grafana org don't have a file like this; Grafana seems to be one of the exceptions to the rule.

We're still waiting for advise about whether it's fine to have a file like this, and whether we should have it at all. If we're advised to add this file, we'll make sure you receive co-authorship for credit for your contribution here.

**Pull request closed without merging**
