### PR TITLE
Add an "exclude_event_message" argument to loki.source.windowsevent

### LINKED ISSUE #4851: Sync loki.source.windowsevent with Promtail 2.8.4

### PR DESCRIPTION
**Pull request by ptodev**
#### PR Description

Syncs the `loki.source.windowsevent` flow component with a [change](https://github.com/grafana/loki/pull/7462) done in promtail a few months ago. Interestingly, this config entry exists in the Agent codebase but was always set to false. I don't know why that is the case. Probably it was an oversight.

#### Which issue(s) this PR fixes

Fixes #4851

#### PR Checklist

- [x] CHANGELOG.md updated
- [x] Documentation added
- [x] Tests updated
- [x] Config converters updated

### CODE REVIEW

**Review by wildum — APPROVED** [review]
LGTM, good catch!

**Review by tpaschalis — APPROVED** [review]
LGTM. This looks like it's the only change since the original introduction of the component.

Coule you please add a `// NOTE:` header so we keep track of the latest Promtail commit we've checked for changes against (in this case, bde65667f7c88af17b7729e3621d7bd5d1d3b45f) to make our job easier if we have to re-sync these components?

**Comment by ptodev** [comment]
> Coule you please add a `// NOTE:` header so we keep track of the latest Promtail commit we've checked for changes against (in this case, bde65667f7c88af17b7729e3621d7bd5d1d3b45f) to make our job easier if we have to re-sync these components?

@tpaschalis  Shouldn't it be 07cbef92268a? That's the version of `github.com/grafana/loki` which we have in the go.mod.

I'm happy to add such a comment, but tbh I'm not sure how much I would trust it in the future. I think this approach to updating Promtail dependencies definitely needs a bigger reform. E.g. it'd be nice if we could at least use specific versions of Promtail instead of commits.

**Review by clayton-cornell — APPROVED** [review]
Docs look good

**Pull request merged**
