### PR TITLE
Prepare for v.30.0-rc.0 release

### PR DESCRIPTION
**Pull request by jcreixell**

### CODE REVIEW

**Comment by tpaschalis** [comment]
Let's also add a header for v0.30 `docs/sources/upgrade-guide/_index.md`.

Don't worry about the `publish-technical-documentation-version / sync (push)` failing, it's due to the fact that we have no matching tag released, as we don't want to publish docs from a branch before the proper (non-RC) release is out.

**Review by karengermond — APPROVED** [review]
LGTM

**Comment by jcreixell** [comment]
Thanks for the reviews, I will close this in favor of another branch to make sure my email matches my gpg signature, sorry for the noise

**Comment by jcreixell** [comment]
closed in favor of #2622

**Pull request closed without merging**
