### PR TITLE
Bump otel collector version to v0.21.0

### LINKED ISSUE #405: Tracing: Grafana Agent retries errors it should not
The OTEL collector has a bug where it will retry errors it shouldn't.  The fix is here:

https://github.com/open-telemetry/opentelemetry-collector/pull/2455

When this is merged and let's upgrade to catch the fix.

### LINKED ISSUE #429: Update go.opentelemetry.io/collector to v0.21.0
An update for `go.opentelemetry.io/collector` (version `v0.21.0`) is now available. Version `v0.16.0` is currently in use.

### PR DESCRIPTION
**Pull request by mapno**
#### PR Description

Bump otel collector to v0.21.0 to include fix for retry errors.

#### Which issue(s) this PR fixes

Closes #405 
Closes #429 

#### Notes to the Reviewer

Retry is now moved to the exporter. The OTLP exporter used in the agent implements the retry mechanism.

#### PR Checklist

- [x] CHANGELOG updated 
- [x] Documentation added
- [x] Tests updated

### CODE REVIEW

**Comment by mapno** [comment]
I think there is nothing config-related to change really. Let me know if I missed something.

**Comment by rfratto** [comment]
Thanks!

> I think there is nothing config-related to change really. Let me know if I missed something.

I think you might have to update the URLs throughout the docs and `pkg/tempo` to v0.21.0, especially if the queued processor settings are define somewhere else now.

**Comment by mapno** [comment]
Oh, right. Updated, thanks!

**Review by joe-elliott — APPROVED** [review]
It looks like the work was already done to map the retry settings to the exporters instead of the retry processor?

**Review by rfratto — APPROVED** [review]
LGTM!

> It looks like the work was already done to map the retry settings to the exporters instead of the retry processor?

Yeah, someone did that but I can't remember who at the moment. Might've been @mdisibio?

**Pull request merged**
