### PR TITLE
[RFC] New Metrics subsystem

### LINKED ISSUE #872: Per-target sharding
The scraping service shards on individual configuration files and _not_ discovered targets. This means efficient use of the scraping service requires users to have [single static configurations for each target](https://github.com/grafana/agent/blob/v0.16.0/docs/scraping-service.md#best-practices). 

This also caused the need for instance sharing, which has performance issues at scale (amplifying the effects of #849), and confuses users due to how it renames remote_write configuration blocks. 

I propose a second layer of sharding for clustered agents, one that shards individual targets and distributes per-target load amongst the cluster. Note that this treats each target as equal, so very large targets with a lot of series would still cause some imbalance. 

I have a design document for per-target sharding [here](https://docs.google.com/document/d/1JI804iaut6bKvZprOydes3Gb5Awo_J0sX-3ORlyc5l0/edit). It has also been partially prototyped [here](https://github.com/rfratto/agent/tree/per-target-sharding), though the prototype uses Pastry for clustering, which I would recommend swapping out with [rfratto/ckit](https://github.com/rfratto/ckit) for the "real" implementation.

### PR DESCRIPTION
**Pull request by rfratto**
Proposes a new metrics subsystem to resolve all of #872, #873, #875, and #888. 

Historically based on the existing [per-target sharding][per-target sharding] proposal, though has some changes to simplify the implementation.  

[per-target sharding]: https://docs.google.com/document/d/1JI804iaut6bKvZprOydes3Gb5Awo_J0sX-3ORlyc5l0

### CODE REVIEW

**Comment by mattdurham** [comment]
Is there an inherent relationship between discovery sources and targets, so that if a discovery source changes those changes are propagated downstream? IE discovery source is no longer valid so all the targets need to be removed from the running systems?

**Comment by rfratto** [comment]
> Thoughts on splitting up the config distribution and target distribution into separate items/executables? Then the agent can assume it is consuming the already "distributed" targets. This feels like a lot of responsibility in one executable.
 
It's not impossible, this is what OpenTelemetry Operator is going to do (or already does, I'm not up to date on the status). I have some concerns, but just so I understand, how would targets be given to the agent? Could you write this up a little more somewhat formally? 

> Is there an inherent relationship between discovery sources and targets, so that if a discovery source changes those changes are propagated downstream? IE discovery source is no longer valid so all the targets need to be removed from the running systems?

It would work like Prometheus: if a SD config becomes invalid, the last set of discovered targets will continue to exist until either the SD config becomes valid again or is updated. To put another way, the proposal here keeps the same semantics of the SD channel but adds sharding and pushes the targets over the network.

**Comment by mattdurham** [comment]
Thoughts on having some scaling tests/environment/conceptual that need to pass before this becomes out of experimental? 

Something like 1k nodes with 100k configs with performance X, or some comparison.

**Comment by rfratto** [comment]
> Thoughts on having some scaling tests/environment/conceptual that need to pass before this becomes out of experimental?

Definitely a good idea, though maybe out of scope for the RFC, and can be discussed after the experiment is initially released and people start playing around with it.

**Comment by rfratto** [comment]
It feels like we've had consensus on this for a while now; taking out of draft.

**Comment by rfratto** [comment]
I'm assigning this RFC-0003 and enabling auto-merge.

**Pull request merged**
