### PR TITLE
Update migration topic to use codeblock for static and flow commands

### PR DESCRIPTION
**Pull request by clayton-cornell**
#### PR Description

This PR updates the migration topics to use the `code` shortcode to show the CLI command for both Static and Flow binaries.

#### PR Checklist

- [ ] CHANGELOG.md updated
- [ ] Documentation added
- [ ] Tests updated
- [ ] Config converters updated

### CODE REVIEW

**Comment by clayton-cornell** [comment]
Static:
image

Flow:
image

**Comment by clayton-cornell** [comment]
@erikbaranowski if this works I can update the other topcis as well:

* https://grafana.com/docs/agent/latest/flow/getting-started/migrating-from-prometheus/
* https://grafana.com/docs/agent/latest/flow/getting-started/migrating-from-promtail/

**Comment by erikbaranowski** [comment]
> @erikbaranowski if this works I can update the other topcis as well:
> 
> * https://grafana.com/docs/agent/latest/flow/getting-started/migrating-from-prometheus/
> * https://grafana.com/docs/agent/latest/flow/getting-started/migrating-from-promtail/

yup looks good to me, thanks

**Comment by clayton-cornell** [comment]
@erikbaranowski Updated for all three topics

I also removed the semicolon after `AGENT_MODE=flow` per a change from a few days ago in the migrate form static topic that wasn't done in the other two migration topics.

**Review by erikbaranowski — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
