### PR TITLE
Fix permissions for WAL data directory

### LINKED ISSUE #1471: Incorrect permissions for /var/lib/grafana-agent directory in RPM install
I installed the most recent RPM onto a GCloud CentOS image and attempted to then start the service. The service startup failed due to incorrect permissions on th `/var/lib/grafana-agent` directory.

```
sudo yum install -y https://github.com/grafana/agent/releases/download/v0.23.0/grafana-agent-0.23.0-1.amd64.rpm
Loaded plugins: fastestmirror
grafana-agent-0.23.0-1.amd64.rpm                                                                                                                                                                                 |  55 MB  00:00:00
Examining /var/tmp/yum-root-LC4Xxy/grafana-agent-0.23.0-1.amd64.rpm: grafana-agent-0.23.0-1.x86_64
Marking /var/tmp/yum-root-LC4Xxy/grafana-agent-0.23.0-1.amd64.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package grafana-agent.x86_64 0:0.23.0-1 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

========================================================================================================================================================================================================================================
 Package                                                Arch                                            Version                                            Repository                                                              Size
========================================================================================================================================================================================================================================
Installing:
 grafana-agent                                          x86_64                                          0.23.0-1                                           /grafana-agent-0.23.0-1.amd64                                          197 M

Transaction Summary
========================================================================================================================================================================================================================================
Install  1 Package

Total size: 197 M
Installed size: 197 M
```
Here is the permissions for the /var/lib/grafana-agent directory immediately after the install.
```
 ls -la /var/lib/
total 8
drwxr-xr-x. 26 root          root          4096 Mar  7 20:02 .
drwxr-xr-x. 18 root          root           254 Mar  7 20:02 ..
drwxr-xr-x.  2 root          root            55 Mar  3 04:50 alternatives
drwxr-xr-x.  2 chrony        chrony           6 Aug  8  2019 chrony
drwxr-xr-x.  2 root          root             6 Sep 30  2020 dbus
drwxr-xr-x.  2 root          root            57 Mar  7 20:02 dhclient
drwxr-xr-x.  2 root          root             6 Apr 11  2018 games
drwxr-xr-x.  2 root          root            26 Mar  7 20:02 google
drwxr-xr-x.  2 root          root             6 Mar  7 20:02 google_osconfig_agent
d---------.  2 grafana-agent grafana-agent    6 Mar  7 20:02 grafana-agent
```

When I attempted to start the service, it died with permission errors in /var/lib/grafana-agent.

```
$ sudo systemctl status -l grafana-agent
● grafana-agent.service - Monitoring system and forwarder
   Loaded: loaded (/usr/lib/systemd/system/grafana-agent.service; disabled; vendor preset: disabled)
   Active: active (running) since Mon 2022-03-07 20:14:23 UTC; 26s ago
     Docs: https://grafana.com/docs/agent/latest/
 Main PID: 1572 (grafana-agent)
   CGroup: /system.slice/grafana-agent.service
           └─1572 /usr/bin/grafana-agent --config.file /etc/grafana-agent.yaml

Mar 07 20:14:28 instance-1 grafana-agent[1572]: ts=2022-03-07T20:14:28.789827198Z caller=instance.go:314 level=error agent=prometheus instance=243a344db344241f404868d04272fc76 msg="failed to initialize instance" err="error creating WAL: create dir: mkdir /var/lib/grafana-agent/243a344db344241f404868d04272fc76: permission denied"
Mar 07 20:14:28 instance-1 grafana-agent[1572]: ts=2022-03-07T20:14:28.789877498Z caller=manager.go:267 level=error agent=prometheus msg="instance stopped abnormally, restarting after backoff period" err="failed to initialize instance: error creating WAL: create dir: mkdir /var/lib/grafana-agent/243a344db344241f404868d04272fc76: permission denied" backoff=5s instance=243a344db344241f404868d04272fc76
Mar 07 20:14:33 instance-1 grafana-agent[1572]: ts=2022-03-07T20:14:33.790538225Z caller=instance.go:314 level=error agent=prometheus instance=243a344db344241f404868d04272fc76 msg="failed to initialize instance" err="error creating WAL: create dir: mkdir /var/lib/grafana-agent/243a344db344241f404868d04272fc76: permission denied"
```

After performing a `chmod o=rwx` on the directory, this service came up. 

Please fix the RPM to set the `/var/lib/grafana-agent` permissions so that the service may start.

### PR DESCRIPTION
**Pull request by rfratto**
Fixes #1471

### CODE REVIEW

**Comment by rfratto** [comment]
(Do we have an easy way of testing this change? I'm pretty sure this will do it but instructions for manual testing should be something we document somewhere.)

cc @jdbaldry if you remember how to test these

**Comment by jdbaldry** [comment]
There's a `test-packages` target in the Makefile (https://github.com/grafana/agent/blob/main/Makefile#L477-L479). I'm not sure how much the underlying script would have degraded though so it may need some TLC. Let me know if you need someone to take a look at that and I'll put it on my list for tomorrow.

**Comment by rfratto** [comment]
Thanks Jack! I can look into it, no need for you to spend time on it. 

Also, it's late for you, stop looking at Github :)

**Review by tpaschalis — APPROVED** [review]
Looks simple enough! ^^

**Pull request merged**
