### PR TITLE
grafana agent is available as linux packages

### PR DESCRIPTION
**Pull request by speculatrix**
#### PR Checklist

- [ ] CHANGELOG updated
- [x] Documentation added
- [ ] Tests updated

### CODE REVIEW

**Review by karengermond — APPROVED** [review]
LGTM

**Comment by speculatrix** [comment]
updated having had feedback

**Comment by marctc** [comment]
@speculatrix CLA is required to be signed before merging. Could you do it? thanks

**Comment by speculatrix** [comment]
> @speculatrix CLA is required to be signed before merging. Could you do it? thanks

Done!

**Comment by marctc** [comment]
> > @speculatrix CLA is required to be signed before merging. Could you do it? thanks
> 
> Done!

I think you might need to force push after signing. I still can't merge the PR

**Comment by marctc** [comment]
@speculatrix could you fix conflicts and review sign the cla? thanks

**Comment by marctc** [comment]
@clayton-cornell I think you are working on this page right now, do you want include these changes or we close the PR?

**Comment by speculatrix** [comment]
I tried a git push --force and it didn't do anything. I don't know what else to do. Too much effort for a relatively trivial change.

it's probably easier for a maintainer to take the bits of my suggested file as part of any maintenance they're doing along the way, so I'm going to close this PRq.

**Comment by clayton-cornell** [comment]
OK, looking at this PR... there's conflict issues that are difficult to resolve - the git rebase starts pulling in a bunch of unrelated files and things start getting messy with teh backporting I need to do to fix things in previous doc releases. So... to make everyone's lives easier, I think I will roll up the suggested changes from this PR into a newer PR I'm working on.

**Comment by clayton-cornell** [comment]
@speculatrix I'm going to close this PR. The changes you requested were rolled into https://github.com/grafana/agent/pull/4355 and more changes are pending as I work on this area of the documentation.

**Pull request closed without merging**
