### PR TITLE
Use Defined types in client arguments

### PR DESCRIPTION
**Pull request by dosmanak**
use types as defined as https://grafana.com/docs/agent/latest/flow/config-language/expressions/types_and_values/

#### PR Checklist

- [ ] CHANGELOG updated
- [ ] Documentation added
- [ ] Tests updated

### CODE REVIEW

**Review by tpaschalis — CHANGES_REQUESTED** [review]

**Comment by dosmanak** [comment]
Thanks for ultra fast reaction.
I was not sure how the type `map(string)` shall be formatted.
I decided to go with
```
  client {                                                                                              
    endpoint = env("TEMPO_URL")                                                                         
    auth = otelcol.auth.basic.tempocreds.handler                                                        
    headers = {                                                                                           
      "X-Scope-OrgID" = env("TEMPO_TENANT_ID")                                                          
    }                                                                                                   
  }        
```

**Comment by tpaschalis** [comment]
> I was not sure how the type map(string) shall be formatted.

The idea here was that map keys are always strings, so the `map(T)` describes what `T` type the values should take, so in this case it's a `string -> string` map.

If you don't mind, I'm closing this PR. We'll keep an eye out for things we can improve in the documentation; feel free to propose such documentation changes via another PR or an issue.

Thanks again!

**Comment by rfratto** [comment]
@tpaschalis Should we document our type naming convention somewhere so people know what "duration" means?

**Comment by tpaschalis** [comment]
> @tpaschalis Should we document our type naming convention somewhere so people know what "duration" means?
Yes. I think the "Types and Values" page may be a good candidate, under "Special Types". WDYT?

**Comment by rfratto** [comment]
> Yes. I think the "Types and Values" page may be a good candidate, under "Special Types". WDYT?

SGTM, but given the above comment I think we should also have a table or something somewhere which mentions every type used in the docs:

`boolean`
`number`
`string`
`map(T)` 
`array(T)` 
`duration` 
`capsule(T)`

This also might be a good opportunity to reconsider if `map(T)` should be `object(T)`.

**Pull request closed without merging**
