### PR TITLE
Remove duplicated oauth2 key from metricsinstances

### PR DESCRIPTION
**Pull request by daper**
#### PR Description
Remove duplicated oauth2 key on metricsinstances CRD

#### Which issue(s) this PR fixes
- #2534 

#### PR Checklist

- [x] CHANGELOG updated
- [ ] Documentation added
- [ ] Tests updated

### CODE REVIEW

**Comment by marctc** [comment]
Hey @daper, thanks for the PR! Did you remove those lines manually or running `make gen-crds`?

**Comment by daper** [comment]
> Hey @daper, thanks for the PR! Did you remove those lines manually or running `make gen-crds`?

Manually, yes...

**Comment by daper** [comment]
I've updated my commit issuing `make generate-crds USE_CONTAINER=1`. @marctc

**Review by marctc — APPROVED** [review]
Thanks!

**Pull request merged**
