### PR TITLE
Installation fails with "The response content cannot be parsed..."

### PR DESCRIPTION
**Pull request by stefanes**
Installation fails with with the following error:
```powershell
Retrieving and updating Grafana agent config
Invoke-WebRequest : The response content cannot be parsed because the Internet Explorer engine is not available, or Int
ernet Explorer's first-launch configuration is not complete. Specify the UseBasicParsing parameter and try again.
At C:\work\grafanacloud-install.ps1:52 char:13
+ $response = Invoke-WebRequest $CONFIG_URI -Method 'GET' -Headers $hea ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotImplemented: (:) [Invoke-WebRequest], NotSupportedException
    + FullyQualifiedErrorId : WebCmdletIEDomNotSupportedException,Microsoft.PowerShell.Commands.InvokeWebRequestComman
   d

ConvertFrom-Json : Cannot bind argument to parameter 'InputObject' because it is null.
At C:\work\grafanacloud-install.ps1:54 char:24
+ $jsonObj = $response | ConvertFrom-Json
+                        ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [ConvertFrom-Json], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.ConvertFrom
   JsonCommand

Failed to retrieve config
```

This error is fixed by adding the `-UseBasicParsing` parameter to `Invoke-WebRequest` command.

#### PR Checklist

- [ ] CHANGELOG updated
- [ ] Documentation added
- [ ] Tests updated

### CODE REVIEW

**Comment by tpaschalis** [comment]
Thank you for the PR Stefan!

I'm cc-ing @mshahzeb for a quick check. For posterity, can you provide some details about what version of Windows you encountered this at?

**Comment by stefanes** [comment]
Found this on a relatively fresh Windows 10 Home box:
```
Edition         Windows 10 Home
Version         22H2
Installed on    2022-‎10-‎19
OS build        19045.2364
Experience      Windows Feature Experience Pack 120.2212.4190.0
```

**Review by mshahzeb — APPROVED** [review]
LGTM!

**Comment by rfratto** [comment]
Thank you!

**Pull request merged**
